# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="{{colors.surface.default.hex}}"

# Main text color
theme[main_fg]="{{colors.on_surface.default.hex}}"

# Title color for boxes
theme[title]="{{colors.primary.default.hex}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{colors.tertiary.default.hex}}"

# Background color of selected item in processes box
theme[selected_bg]="{{colors.surface_variant.default.hex}}"

# Foreground color of selected item in processes box
theme[selected_fg]="{{colors.on_surface_variant.default.hex}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{colors.outline.default.hex}}"

# Color of text appearing on top of graphs, ie uptime and current network graph scaling
theme[graph_text]="{{colors.on_surface_variant.default.hex}}"

# Background color of the percentage meters
theme[meter_bg]="{{colors.surface_container_highest.default.hex}}"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{colors.secondary.default.hex}}"

# Cpu box outline color
theme[cpu_box]="{{colors.primary.default.hex}}"

# Memory/disks box outline color
theme[mem_box]="{{colors.secondary.default.hex}}"

# Net up/down box outline color
theme[net_box]="{{colors.tertiary.default.hex}}"

# Processes box outline color
theme[proc_box]="{{colors.primary_fixed.default.hex}}"

# Box divider line and small boxes line color
theme[div_line]="{{colors.outline_variant.default.hex}}"

# Temperature graph colors
theme[temp_start]="{{colors.primary.default.hex}}"
theme[temp_mid]="{{colors.secondary.default.hex}}"
theme[temp_end]="{{colors.error.default.hex}}"

# CPU graph colors
theme[cpu_start]="{{colors.primary.default.hex}}"
theme[cpu_mid]="{{colors.secondary.default.hex}}"
theme[cpu_end]="{{colors.tertiary.default.hex}}"

# Mem/Disk free meter
theme[free_start]="{{colors.primary_container.default.hex}}"
theme[free_mid]="{{colors.primary_container.default.hex}}"
theme[free_end]="{{colors.primary_container.default.hex}}"

# Mem/Disk cached meter
theme[cached_start]="{{colors.secondary_container.default.hex}}"
theme[cached_mid]="{{colors.secondary_container.default.hex}}"
theme[cached_end]="{{colors.secondary_container.default.hex}}"

# Mem/Disk available meter
theme[available_start]="{{colors.tertiary_container.default.hex}}"
theme[available_mid]="{{colors.tertiary_container.default.hex}}"
theme[available_end]="{{colors.tertiary_container.default.hex}}"

# Mem/Disk used meter
theme[used_start]="{{colors.error_container.default.hex}}"
theme[used_mid]="{{colors.error_container.default.hex}}"
theme[used_end]="{{colors.error_container.default.hex}}"

# Download graph colors
theme[download_start]="{{colors.primary.default.hex}}"
theme[download_mid]="{{colors.primary.default.hex}}"
theme[download_end]="{{colors.primary.default.hex}}"

# Upload graph colors
theme[upload_start]="{{colors.tertiary.default.hex}}"
theme[upload_mid]="{{colors.tertiary.default.hex}}"
theme[upload_end]="{{colors.tertiary.default.hex}}"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="{{colors.primary.default.hex}}"
theme[process_mid]="{{colors.secondary.default.hex}}"
theme[process_end]="{{colors.tertiary.default.hex}}"
