# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#131313"

# Main text color
theme[main_fg]="#e2e2e2"

# Title color for boxes
theme[title]="#ffffff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e2e2e2"

# Background color of selected item in processes box
theme[selected_bg]="#474747"

# Foreground color of selected item in processes box
theme[selected_fg]="#c6c6c6"

# Color of inactive/disabled text
theme[inactive_fg]="#919191"

# Color of text appearing on top of graphs, ie uptime and current network graph scaling
theme[graph_text]="#c6c6c6"

# Background color of the percentage meters
theme[meter_bg]="#353535"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c6c6c6"

# Cpu box outline color
theme[cpu_box]="#ffffff"

# Memory/disks box outline color
theme[mem_box]="#c6c6c6"

# Net up/down box outline color
theme[net_box]="#e2e2e2"

# Processes box outline color
theme[proc_box]="#5e5e5e"

# Box divider line and small boxes line color
theme[div_line]="#474747"

# Temperature graph colors
theme[temp_start]="#ffffff"
theme[temp_mid]="#c6c6c6"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#ffffff"
theme[cpu_mid]="#c6c6c6"
theme[cpu_end]="#e2e2e2"

# Mem/Disk free meter
theme[free_start]="#d4d4d4"
theme[free_mid]="#d4d4d4"
theme[free_end]="#d4d4d4"

# Mem/Disk cached meter
theme[cached_start]="#474747"
theme[cached_mid]="#474747"
theme[cached_end]="#474747"

# Mem/Disk available meter
theme[available_start]="#919191"
theme[available_mid]="#919191"
theme[available_end]="#919191"

# Mem/Disk used meter
theme[used_start]="#93000a"
theme[used_mid]="#93000a"
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#ffffff"
theme[download_mid]="#ffffff"
theme[download_end]="#ffffff"

# Upload graph colors
theme[upload_start]="#e2e2e2"
theme[upload_mid]="#e2e2e2"
theme[upload_end]="#e2e2e2"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#ffffff"
theme[process_mid]="#c6c6c6"
theme[process_end]="#e2e2e2"
