background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 5
    noise = 0.015
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

# Imagen de Avatar
image {
    monitor =
    path = ~/.config/hypr/avatar.jpeg
    size = 130
    border_size = 4
    border_color = rgb(255, 255, 255)
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 10
}

# Reloj muy visual (Horas en negrita, minutos más suaves)
label {
    monitor =
    text = cmd[update:1000] echo "<span font_weight='ultrabold'>$(date +"%H")</span><span foreground='##ffffff99'>$(date +"%M")</span>"
    color = rgba(255, 255, 255, 1)
    font_size = 160
    font_family = sans-serif
    position = 0, 320
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 20
}

# Fecha con estilo
label {
    monitor =
    text = cmd[update:1000] echo "<span foreground='##ffffff99'>$(date +"%A, ")</span><span font_weight='bold'>$(date +"%d %B")</span>"
    color = rgba(255, 255, 255, 1)
    font_size = 28
    font_family = sans-serif
    position = 0, 190
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 10
}

# Caja de contraseña muy redondeada y visual
input-field {
    monitor =
    size = 280, 60
    outline_thickness = 4
    dots_size = 0.3 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(255, 255, 255, 0.8)
    inner_color = rgba(0, 0, 0, 0.6)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    font_family = sans-serif
    placeholder_text = <i><span foreground="##ffffff99">    Entrar...</span></i>
    hide_input = false
    position = 0, -90
    halign = center
    valign = center
    rounding = -1
    check_color = rgb(235, 160, 45)
    fail_color = rgb(235, 60, 60)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    shadow_passes = 2
    shadow_size = 10
}

# Widget de batería inferior
label {
    monitor =
    text = cmd[update:1000] echo "🔋 Batería: $(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null || echo '100')%"
    color = rgba(255, 255, 255, 0.6)
    font_size = 18
    font_family = sans-serif font-weight:bold
    position = 0, 50
    halign = center
    valign = bottom
    shadow_passes = 1
    shadow_size = 5
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 3, linear
}
