[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=assets/background.jpg

# Colors
accentColor=#A9C78F
autoColor=true
use24HourClock=false
backgroundColor=#1A1C18
textColor=#E3E3DC

# Font family. Override with any installed system font.
fontFamily=
