[config]
wallpaper_set = false

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/matugen-colors.conf"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.bash]
input_path = "~/.config/matugen/templates/bash-colors.sh"
output_path = "~/.cache/theme_thumbnails/matugen_colors.sh"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout-colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.btop]
input_path = "~/.config/matugen/templates/btop-colors.theme"
output_path = "~/.config/btop/themes/matugen.theme"

